test_that("report packaging bundle is registry-driven, checksummed, and offline", {
  fx <- file.path(tempdir(), "report_package_fixture"); unlink(fx, recursive = TRUE)
  dir.create(file.path(fx, "d"), recursive = TRUE); dir.create(file.path(fx, "m"))
  tab <- data.frame(category_id = c("P01", "P02"), symbol = c("SGS", "STAT3"), mean_NES = c(1.2, -0.4), stringsAsFactors = FALSE)
  write.table(tab, file.path(fx, "d", "T0001.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  reg <- data.frame(table_id = "T0001", path = "d/T0001.tsv", role = "single_de/category_gene_evidence", analysis_id = "A", contrast_id = NA_character_, collection = "PATHWAYS", sha256 = lisaR:::lisa_report_package_sha256(file.path(fx, "d", "T0001.tsv")))
  write.table(reg, file.path(fx, "m", "registry.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(analysis_id = "A", label = "Transcriptomic SGS"), file.path(fx, "m", "de.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(contrast_id = "C", contrast_label = "A versus B"), file.path(fx, "m", "cx.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(analysis_collection = "PATHWAYS"), file.path(fx, "m", "col.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(source_path = "archived/output.tsv", role = "canonical", source_sha256 = reg$sha256), file.path(fx, "m", "prov.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  files <- sort(list.files(fx, recursive = TRUE, full.names = FALSE)); write.table(data.frame(path = files, sha256 = vapply(file.path(fx, files), lisaR:::lisa_report_package_sha256, character(1))), file.path(fx, "m", "sha256.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  out_parent <- tempfile("report_package_output-")
  dir.create(out_parent)
  out <- file.path(out_parent, ".", "bundle")
  result <- build_lisa_report_package(fx, out)
  expect_identical(
    dirname(result$index), normalizePath(out, winslash = "/", mustWork = TRUE)
  )
  expect_true(file.exists(result$index)); expect_true(file.exists(file.path(out, "d", "report.xlsx"))); expect_true(file.exists(file.path(out, "d", "tables.zip")))
  expect_identical(readBin(file.path(out, "d", "T0001.csv"), "raw", n = 3L), as.raw(c(0xef, 0xbb, 0xbf)))
  expect_equal(read.csv(file.path(out, "d", "T0001.csv"), fileEncoding = "UTF-8-BOM", check.names = FALSE)$symbol, tab$symbol)
  long_root <- file.path(tempdir(), paste(rep("windows-safe-root", 10L), collapse = "-")); unlink(long_root, recursive = TRUE); dir.create(long_root, recursive = TRUE)
  utils::unzip(file.path(out, "d", "tables.zip"), exdir = long_root)
  expect_true(file.exists(file.path(long_root, "T0001.csv")))
  expect_true(lisaR:::lisa_report_foundation_verify_links(out)); expect_lte(result$max_path, 120L); expect_lte(result$max_html, 1024^2)
  m <- read_lisa_tsv(file.path(out, "m", "manifest.tsv")); expect_true(all(vapply(seq_len(nrow(m)), function(i) identical(lisaR:::lisa_report_package_sha256(file.path(out, m$path[[i]])), m$sha256[[i]]), logical(1))))
  expect_equal(openxlsx::sheets(openxlsx::loadWorkbook(file.path(out, "d", "report.xlsx")))[1], "README")
  malformed <- read_lisa_tsv(file.path(fx, "m", "sha256.tsv"))
  malformed$sha256[[1]] <- ""
  write.table(malformed, file.path(fx, "m", "sha256.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  expect_error(lisaR:::lisa_report_package_read_fixture(fx), "manifest is malformed")
})

test_that("report packaging fixture rejects incomplete material", {
  fx <- tempfile("report_package_invalid-"); dir.create(file.path(fx, "m"), recursive = TRUE); writeLines("x", file.path(fx, "m", "registry.tsv"))
  expect_error(lisaR:::lisa_report_package_read_fixture(fx), "incomplete")
})

test_that("report packaging alias matching and XLSX NA checks are explicit", {
  expect_identical(lisaR:::lisa_report_package_has_alias(c("A|B", "AA", ""), "A"), c(TRUE, FALSE, FALSE))
  expect_identical(lisaR:::lisa_report_package_visual_product("results/leading_edge_ge_ab12/plot.png"), "heatmaps")
  td <- tempfile("w8xlsx-"); dir.create(td)
  write.table(data.frame(value = c(NA_character_, "ok")), file.path(td, "T0001.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  reg <- data.frame(table_id = "T0001", role = "test", stringsAsFactors = FALSE)
  out <- tempfile(fileext = ".xlsx")
  info <- lisaR:::lisa_report_package_write_xlsx(reg, td, out)
  expect_true(file.exists(out))
  expect_equal(info$included, 1L)
  expect_equal(info$csv_only, 0L)

  writeLines("", file.path(td, "T0002.tsv"))
  empty_info <- lisaR:::lisa_report_package_write_xlsx(data.frame(table_id = "T0002", role = "empty"), td, tempfile(fileext = ".xlsx"))
  expect_equal(empty_info$included, 0L)
  expect_equal(empty_info$csv_only, 1L)
})

test_that("report packaging annotated profile is effective all-true and auditable", {
  fx <- file.path(tempdir(), "report_package_fixture-annotated"); unlink(fx, recursive = TRUE)
  dir.create(file.path(fx, "d"), recursive = TRUE); dir.create(file.path(fx, "g")); dir.create(file.path(fx, "m"))
  write.table(data.frame(symbol = "STAT3"), file.path(fx, "d", "T0001.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  writeLines("<svg xmlns=\"http://www.w3.org/2000/svg\"><rect width=\"5\" height=\"5\"/></svg>", file.path(fx, "g", "F0001.svg"))
  reg <- data.frame(table_id = c("T0001", "F0001"), path = c("d/T0001.tsv", "g/F0001.svg"), artifact_type = c("table", "figure"), role = c("single_de/category_gene_evidence", "single_de/gene_cards/example.svg"), analysis_id = "A", contrast_id = "", collection = "PATHWAYS", sha256 = vapply(file.path(fx, c("d/T0001.tsv", "g/F0001.svg")), lisaR:::lisa_report_package_sha256, character(1)), stringsAsFactors = FALSE)
  write.table(reg, file.path(fx, "m", "registry.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(analysis_id = "A", label = "Mouse protein"), file.path(fx, "m", "de.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(contrast_id = character()), file.path(fx, "m", "cx.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(analysis_collection = "PATHWAYS"), file.path(fx, "m", "col.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(table_id = reg$table_id, source_path = c("x.tsv", "x.svg"), artifact_type = reg$artifact_type, source_sha256 = reg$sha256), file.path(fx, "m", "prov.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  files <- sort(list.files(fx, recursive = TRUE, full.names = FALSE)); write.table(data.frame(path = files, sha256 = vapply(file.path(fx, files), lisaR:::lisa_report_package_sha256, character(1))), file.path(fx, "m", "sha256.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)

  minimal <- tempfile("w8-min-"); annotated <- tempfile("w8-all-")
  build_lisa_report_package(fx, minimal, "minimal")
  result <- build_lisa_report_package(fx, annotated, "annotated")
  expect_false(file.exists(file.path(minimal, "g", "F0001.svg")))
  expect_true(file.exists(file.path(annotated, "g", "F0001.svg")))
  expect_equal(result$figures, 1L)
  options <- read_lisa_tsv(file.path(annotated, "m", "options.tsv"))
  expect_true(all(as.logical(options$value)))
  qc <- read_lisa_tsv(file.path(annotated, "m", "qc.tsv"))
  expect_equal(qc$state[qc$product == "gene_cards"], "PASS")
  expect_equal(qc$state[qc$product == "kegg_maps"], "not_available")
  expect_true(lisaR:::lisa_report_foundation_verify_links(annotated))
})
