test_that("missing-product completion preserves interrupted families and rejects stale receipts", {
  root <- tempfile("full-family-")
  dir.create(file.path(root, "config"), recursive = TRUE)
  write <- function(x,p) utils::write.table(x,p,sep="\t",quote=FALSE,row.names=FALSE)
  write(data.frame(analysis_id="A",species="Homo sapiens"),file.path(root,"config/de_index.tsv"))
  write(data.frame(contrast_id=character(),output_id=character(),contrast_a=character(),contrast_b=character()),
    file.path(root,"config/contrast_index.tsv"))
  dir.create(file.path(root,"outputs/single_de/A/collection_TEST"),recursive=TRUE)
  gene <- file.path(root,"outputs/gene_level/single_de/A/collection_TEST")
  dir.create(gene,recursive=TRUE)
  write(data.frame(symbol="G"),file.path(gene,"A_TEST_gene_level_gene_category_contributions.tsv"))
  audit <- file.path(root,"audit/full_products");dir.create(audit,recursive=TRUE)
  pending <- file.path(audit,"A__TEST__prioritized_genes.tsv.pending")
  writeLines("interrupted",pending)
  expect_error(lisaR:::lisa_complete_full_products(root),"Interrupted FULL family")
  expect_identical(readLines(pending),"interrupted")
  unlink(pending)
  write(data.frame(path="config/de_index.tsv",sha256="not-valid",input_fingerprint="old"),
    sub("[.]pending$","",pending))
  before <- digest::digest(file=file.path(root,"config/de_index.tsv"),algo="sha256")
  expect_error(lisaR:::lisa_complete_full_products(root),"input or builder changed")
  expect_identical(digest::digest(file=file.path(root,"config/de_index.tsv"),algo="sha256"),before)
  expect_length(list.files(gene,pattern="[.]png$",recursive=TRUE),0L)
})
