test_that("native cards retain distinct recipe references and immutable originals", {
  e <- new.env(parent = globalenv())
  sys.source(system.file("scripts/build_LISA_report.R",package="lisaR"),e)
  e$report_package_dir <- system.file(package="lisaR")
  root <- tempfile("native-recipe-reference-");dir.create(root)
  on.exit(unlink(root,recursive=TRUE),add=TRUE)
  evidence <- file.path(root,"report_pages/evidence/A/GOCC")
  product <- file.path(root,"outputs/gene_level/single_de/A/collection_GOCC/category_gene_cards")
  dir.create(file.path(evidence,"tables"),recursive=TRUE);dir.create(product,recursive=TRUE)
  writeLines('<script type="application/json" id="evidence-data">{"categories":[]}</script>',file.path(evidence,"index.html"))
  write_lisa_tsv(data.frame(key=c("analysis_id","collection"),value=c("A","GOCC")),file.path(evidence,"tables/metadata.tsv"))
  write_lisa_tsv(data.frame(category_id=c("CAT_A","CAT_B")),file.path(evidence,"tables/categories.tsv"))
  for(id in c("CAT_A","CAT_B")) {
    write_lisa_tsv(data.frame(category_id=id),file.path(product,paste0(id,"_source.tsv")))
    writeBin(as.raw(c(137,80,78,71)),file.path(product,paste0(id,".png")))
    writeLines("# preserved old recipe",file.path(product,paste0(id,"_recipe.R")))
  }
  original <- list.files(product,full.names=TRUE);before <- vapply(original,lisa_sha256_file,character(1))
  e$report_attach_category_products(file.path(evidence,"index.html"),
    list(list(product="gene_cards",label="Prioritized genes",path=product)),"A","GOCC",project_dir=root)
  refs <- e$report_category_product_reference_rows(root)
  recipes <- refs[refs$format=="r",]
  expect_equal(nrow(recipes),2L)
  expect_equal(length(unique(recipes$source_path)),2L)
  expect_true(all(startsWith(recipes$source_path,"outputs/report_recipes/")))
  expected <- lisa_sha256_file(system.file("scripts/reproduce_lisa_figure.R",package="lisaR"))
  expect_true(all(recipes$sha256==expected))
  expect_identical(vapply(original,lisa_sha256_file,character(1)),before)
  expect_equal(nrow(refs),6L)
})

test_that("global native indexes enter the portable manifest through table downloads", {
  e<-new.env(parent=globalenv());sys.source(system.file("scripts/build_LISA_report.R",package="lisaR"),e)
  root<-tempfile("native-index-portable-");dir.create(file.path(root,"report_pages"),recursive=TRUE)
  on.exit(unlink(root,recursive=TRUE),add=TRUE)
  dir.create(file.path(root,"outputs/indexes"),recursive=TRUE)
  original<-file.path(root,"outputs/indexes/cards_index.tsv")
  write_lisa_tsv(data.frame(category_id=c("A","B"),value=c(1,2)),original)
  before<-lisa_sha256_file(original)
  page<-file.path(root,"report_pages/analysis.html")
  href<-e$report_unclassified_product_href(original,page)
  expect_match(href,"^../report_files/[0-9a-f]+[.]tsv[.]gz$")
  writeLines(paste0('<html><body><a href="',href,'">Index</a></body></html>'),page)
  writeLines('<html><body><a href="report_pages/analysis.html">Open</a></body></html>',file.path(root,"report_index.html"))
  e$write_shareable_report_manifest(root)
  expect_silent(e$validate_shareable_report_manifest(root))
  manifest<-e$read_shareable_report_manifest(root)
  expect_true(sub("^../","",href)%in%manifest$relative_path)
  expect_false("outputs/indexes/cards_index.tsv"%in%manifest$relative_path)
  expect_identical(lisa_sha256_file(original),before)
})

test_that("native README stays visible without an unlisted private download", {
  e<-new.env(parent=globalenv());sys.source(system.file("scripts/build_LISA_report.R",package="lisaR"),e)
  root<-tempfile("native-readme-");dir.create(file.path(root,"report_pages"),recursive=TRUE)
  on.exit(unlink(root,recursive=TRUE),add=TRUE)
  doc<-file.path(root,"README.txt");writeLines(c("Native heatmaps",paste("Output:",root)),doc)
  html<-e$report_unclassified_product_link(doc,file.path(root,"report_pages/analysis.html"))
  expect_match(html,"Native heatmaps",fixed=TRUE)
  expect_false(grepl(root,html,fixed=TRUE))
  expect_false(grepl("href=",html,fixed=TRUE))
})
