test_that("offline KEGG selection and dual map retain species, compounds, and multi-ID mappings", {
  enrichment <- data.frame(pathway = c("p1", "p2"), padj = c(0.05, 0.051))
  expect_equal(nrow(lisa_kegg_map_selection(enrichment, "Homo sapiens")), 1L)
  expect_equal(nrow(lisa_kegg_map_selection(enrichment, "Mus musculus")), 1L)
  expect_error(lisa_kegg_map_selection(enrichment, "rat"), "unsupported")
  a <- data.frame(gene_id = c("G1", "G2"), log2fc = c(2, 1))
  b <- data.frame(gene_id = c("G1", "G3"), log2fc = c(-3, 4))
  maps <- data.frame(gene_id = c("G1", "G1", "G2", "G3"), node_id = c("hsa:101", "C00031", "hsa:101", "hsa:202"))
  out <- lisa_kegg_dual_node_table(a, b, maps, "Homo sapiens")
  expect_true(any(out$compound_node))
  expect_true(any(out$multi_id_mapping_present))
  expect_identical(out$mapped_gene_ids[out$node_id == "hsa:101"], "G1;G2")
  expect_equal(unique(out$common_scale_max_abs_log2fc), 4)
  expect_true(all(grepl("not painted", out$paint_encoding, fixed = TRUE)))
  expect_true(all(grepl("arithmetic mean", out$node_summarization, fixed = TRUE)))
  expect_equal(out$delta_log2fc_data_only[out$node_id == "hsa:101"], 4.5)
  expect_error(lisa_kegg_dual_node_table(a, b, rbind(maps, maps[1, ]), "Homo sapiens"), "duplicate gene-to-node")
  expect_error(lisa_kegg_dual_node_table(rbind(a, a[1, ]), b, maps, "Homo sapiens"), "duplicate gene_id")
})
