test_that("report foundation external fixture fails closed when absent", {
  expect_error(lisaR:::lisa_report_foundation_fixture(file.path(tempdir(), "missing-contract")), "explicit external audit fixture")
})

test_that("report foundation schema-only report has offline pages and CSV alternative", {
  root <- file.path(tempdir(), "report_foundation_fixture"); unlink(root, recursive = TRUE)
  dir.create(file.path(root, "m"), recursive = TRUE); dir.create(file.path(root, "d")); dir.create(file.path(root, "a"))
  writeLines("<svg xmlns=\"http://www.w3.org/2000/svg\"/>", file.path(root, "a/logo.svg"))
  write.table(data.frame(analysis_collection = "PATHWAYS"), file.path(root, "m/col.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(analysis_id = "A"), file.path(root, "m/de.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(contrast_id = "C"), file.path(root, "m/cx.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(source_path = "canonical/sd.tsv", role = "single_summary", source_sha256 = paste(rep("0", 64), collapse = "")), file.path(root, "m/prov.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(category_id = "X", category_display_name = "Example", n_genesets = 1, mean_NES = 1, min_padj = .01, same_direction_pct = 100, mean_NES_direction = "Positive"), file.path(root, "d/sd.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(contrast_category_rank = 1, category_id = "X", category_display_name = "Example", direction_A = "positive", direction_B = "positive", direction_class = "same", mean_NES_A = 1, mean_NES_B = 1, delta_mean_NES = 0, min_padj_A = .01, min_padj_B = .02, n_shared_same_direction = 2), file.path(root, "d/cx.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(category_id = "X", symbol = "GENE", log2FC_A = 1, padj_A = .01, gene_contribution_score_A = 1, gene_set_id = "GS"), file.path(root, "d/ge.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  paths <- c("a/logo.svg", "m/col.tsv", "m/de.tsv", "m/cx.tsv", "m/prov.tsv", "d/sd.tsv", "d/cx.tsv", "d/ge.tsv")
  sums <- vapply(file.path(root, paths), lisaR:::lisa_report_foundation_sha256, character(1))
  write.table(data.frame(path = paths, sha256 = sums), file.path(root, "m/sha256.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  out <- build_lisa_foundation_report(root, file.path(tempdir(), "report_foundation_output"))
  expect_true(all(file.exists(out[!is.na(out)])))
  report <- dirname(out[["index"]])
  expect_true(all(file.exists(file.path(report, "d", c("s.csv", "c.csv", "s.tsv", "c.tsv", "g.tsv")))))
  expect_identical(readBin(file.path(report, "d", "s.csv"), "raw", n = 3L), as.raw(c(0xef, 0xbb, 0xbf)))
  expect_lt(max(file.info(out[c("index", "single_de", "contrast", "collection")])$size), 1024^2)
  single_html <- paste(readLines(out[["single_de"]], warn = FALSE), collapse = "\n")
  contrast_html <- paste(readLines(out[["contrast"]], warn = FALSE), collapse = "\n")
  index_html <- paste(readLines(out[["index"]], warn = FALSE), collapse = "\n")
  expect_equal(length(gregexpr('class="card bar"', single_html, fixed = TRUE)[[1]]), 3L)
  expect_match(single_html, "Category LISA signal")
  expect_match(single_html, "Mean NES")
  expect_match(single_html, "Same-direction percentage")
  expect_match(contrast_html, "Paired A/B mean NES with delta")
  expect_match(contrast_html, "Delta \\(A - B\\): 0")
  expect_match(index_html, 'href="d/s.csv"', fixed = TRUE)
  expect_match(index_html, 'href="d/c.tsv"', fixed = TRUE)
  expect_match(single_html, 'a/search.js', fixed = TRUE)
  expect_true(file.exists(file.path(report, "a", "search.json")))
  search_js <- paste(readLines(file.path(report, "a", "search.js"), warn = FALSE), collapse = "\n")
  expect_match(search_js, "LISA_SEARCH_INDEX", fixed = TRUE)
  expect_false(grepl("fetch(", search_js, fixed = TRUE))
  expect_true(file.exists(file.path(report, "a", "logo.svg")))
  generated <- read_lisa_tsv(file.path(report, "m", "manifest.tsv"))
  expect_true(all(vapply(seq_len(nrow(generated)), function(i) identical(lisaR:::lisa_report_foundation_sha256(file.path(report, generated$path[[i]])), generated$sha256[[i]]), logical(1))))
  expect_match(paste(readLines(file.path(report, "m", "SHA256SUMS"), warn = FALSE), collapse = "\n"), "m/manifest.tsv", fixed = TRUE)
  expect_true(lisaR:::lisa_report_foundation_verify_links(report))
  if (requireNamespace("openxlsx", quietly = TRUE)) {
    expect_true(file.exists(out[["xlsx"]]))
    expect_equal(openxlsx::sheets(openxlsx::loadWorkbook(out[["xlsx"]])), c("single_de", "contrast", "gene_evidence"))
  } else {
    expect_true(is.na(out[["xlsx"]]))
  }
  malformed <- read_lisa_tsv(file.path(root, "m", "sha256.tsv"))
  malformed$sha256[[1]] <- ""
  write.table(malformed, file.path(root, "m", "sha256.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  expect_error(lisaR:::lisa_report_foundation_fixture(root), "malformed SHA-256 manifest")
})

test_that("report foundation pagination never exceeds 200 cards and preserves every row", {
  root <- file.path(tempdir(), "w7-many"); unlink(root, recursive = TRUE)
  dir.create(file.path(root, "m"), recursive = TRUE); dir.create(file.path(root, "d")); dir.create(file.path(root, "a"))
  writeLines("<svg xmlns=\"http://www.w3.org/2000/svg\"/>", file.path(root, "a/logo.svg"))
  write.table(data.frame(analysis_collection = "PATHWAYS"), file.path(root, "m/col.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(analysis_id = "A"), file.path(root, "m/de.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(contrast_id = "C"), file.path(root, "m/cx.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(source_path = "canonical/sd.tsv", role = "single_summary", source_sha256 = paste(rep("0", 64), collapse = "")), file.path(root, "m/prov.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  n <- 121L
  sd <- data.frame(category_id = sprintf("X%03d", seq_len(n)), category_display_name = sprintf("Example %03d", seq_len(n)), n_genesets = 1, mean_NES = 1, min_padj = .01, same_direction_pct = 100, mean_NES_direction = "Positive")
  cx <- data.frame(contrast_category_rank = seq_len(n), category_id = sd$category_id, category_display_name = sd$category_display_name, direction_A = "positive", direction_B = "positive", direction_class = "same", mean_NES_A = 1, mean_NES_B = 1, delta_mean_NES = 0, min_padj_A = .01, min_padj_B = .02, n_shared_same_direction = 2)
  write.table(sd, file.path(root, "d/sd.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(cx, file.path(root, "d/cx.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(data.frame(category_id = "X001", symbol = "GENE", log2FC_A = 1, padj_A = .01, gene_contribution_score_A = 1, gene_set_id = "GS"), file.path(root, "d/ge.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  paths <- c("a/logo.svg", "m/col.tsv", "m/de.tsv", "m/cx.tsv", "m/prov.tsv", "d/sd.tsv", "d/cx.tsv", "d/ge.tsv")
  write.table(data.frame(path = paths, sha256 = vapply(file.path(root, paths), lisaR:::lisa_report_foundation_sha256, character(1))), file.path(root, "m/sha256.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  out <- tempfile("report-foundation-many-"); build_lisa_foundation_report(root, out)
  pages <- list.files(out, pattern = "^(sd|cx)-[0-9]+\\.html$", full.names = TRUE)
  cards <- vapply(pages, function(p) {
    html <- paste(readLines(p, warn = FALSE), collapse = "\n")
    m <- gregexpr('class="card (?:bar|paired)"', html, perl = TRUE)[[1]]
    if (identical(m, -1L)) 0L else length(m)
  }, integer(1))
  expect_lte(max(cards), 200L)
  expect_equal(sum(cards[grepl("/sd-", pages)]), 3L * n)
  expect_equal(sum(cards[grepl("/cx-", pages)]), n)
  expect_true(lisaR:::lisa_report_foundation_verify_links(out))
})

test_that("report foundation canonical parity fixture is opt-in and explicitly skipped when absent", {
  fixture <- Sys.getenv("LISA_REPORT_FOUNDATION_FIXTURE", unset = "")
  if (!nzchar(fixture) || !dir.exists(fixture)) skip("LISA_REPORT_FOUNDATION_FIXTURE is absent; canonical external-fixture parity was not run.")
  out <- tempfile("contract-parity-")
  pages <- build_lisa_foundation_report(fixture, out)
  expect_true(all(file.exists(pages[!is.na(pages)])))
  expect_lte(max(nchar(normalizePath(list.files(out, recursive = TRUE, full.names = TRUE), winslash = "/"))), 120)
  expect_lte(max(nchar(list.files(out, recursive = TRUE, full.names = FALSE))), 80)
})
