test_that("native source-only repair preserves figures and multiline source fields", {
  builder <- system.file("scripts/build_single_de_category_volcano_overlays.R", package="lisaR")
  env <- new.env(parent=asNamespace("lisaR"))
  env$commandArgs <- function(...) paste0("--file=",builder)
  sys.source(builder,env)
  env$build_volcano <- function(...) stop("Unexpected figure rendering")
  env$lisa_plot_subtitle <- function(...) "First line\nSecond line"
  root<-tempfile();dir.create(root)
  cfg<-env$parse_args(c('--project-dir',root,'--analysis-id','A','--source-only','true'))
  cfg$plot_metadata<-list()
  paths<-list(volcano_dir=root,prefix='A')
  png<-file.path(root,'CAT_category_volcano_overlay.png');writeLines('existing-figure-sentinel',png)
  before<-readBin(png,'raw',n=file.info(png)$size)
  de<-data.frame(symbol=c('X','Y'),log2FC=c(1,-2),neg_log10_fdr=c(2,3),padj=c(.01,.001),de_class=c('DE up','DE down'))
  ev<-data.frame(symbol='X',category_id='CAT',category_display_name='Category',macrogroup_name='Macro',macrogroup_id='M',color='#112233',gene_contribution_score=2,padj=.01)
  index<-env$write_volcanoes(de,ev,'CAT',paths,cfg)
  source<-file.path(root,'CAT_category_volcano_overlay_source.tsv')
  x<-lisaR:::lisa_read_figure_source_tsv(source)
  expect_identical(readBin(png,'raw',n=file.info(png)$size),before)
  expect_equal(nrow(index),1L)
  expect_equal(nrow(x),2L)
  expect_identical(x$figure_type,rep('volcano_overlay',2))
  expect_identical(x$plot_subtitle,rep('First line\nSecond line',2))
  expect_equal(x$log2FC,de$log2FC)
  expect_length(readLines(source),3L)
  unlink(png)
  expect_error(env$write_volcanoes(de,ev,'CAT',paths,cfg),'requires all existing')
})
